### ISSUE TITLE
Fallo al crear un usuario

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax/decide#30]
Cuando se crea un usuario a través del nuevo formulario, hace el método de POST pero ese usuario no aparece en la base de datos.

El error se comete en un navegador Firefox, versión 84.0, con la aplicación desplegado en local. Se han seguido los siguientes pasos:

1.- Se clona la rama de autenticacion-registro.
2.- Se despliega en local.
3.- Se accede al formulario a través de la url http://127.0.0.1:8000/authentication/prueba/
4.- Se crea un usuario correctamente.
5.- Se accede a la vista de admin y en Users no aparece ningún nuevo usuario.

En el log se comprueba que se realiza el POST sin problema, de hecho, repitiendo los pasos pero en el paso 4 introducimos datos incorrectos, no devuelve errores tampoco.

La causa del error debe encontrarse en el archivo views.py del módulo authentication, en la función registro_usuario.

**Comment by PabloRodriguezGarrido11** [comment]
Prueba a seguir todos los pasos de nuevo, cuando probaste la funcionalidad no estaba completo el código de la función que se encarga de guardar el formulario en la base de datos.

**Comment by julsoutos** [comment]
Sí, tienes razón. Ahora funciona.
