### ISSUE TITLE
Fallo protección url

### ISSUE THREAD

**Issue by PabloRodriguezGarrido11** [decide-part-andarax/decide#41]
Se produce un fallo de seguridad en la url posterior a iniciar sesión o al registro de usuario, donde en ambos casos para acceder a esa platilla de bienvenida se está autenticando el usuario para poder acceder a esta.

El error se comete al introducir la url sin haber iniciado sesión en la aplicación. Se han seguido los siguientes pasos:

1.- Iniciamos la aplicación.
2.- Introducimos la url 'localhost/authentication/inicio'.
3.- Como se puede comprobar hemos accedido a esta vista sin habernos autenticado previamente.

Se debe buscar una manera de proteger esta url, de forma que sólo puedan acceder aquellos usuarios que hayan sido autenticados en el sistema.

**Comment by julsoutos** [comment]
Se ha protegido la url añadiendo en el archivo urls.py del módulo authentication el decorador "login_required". Ahora debería funcionar correctamente.

**Comment by PabloRodriguezGarrido11** [comment]
Comprobado, funciona correctamente.
