### ISSUE TITLE
Fallo en la redirección de GitHub

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax/decide#59]
Se produce un fallo al intentar iniciar sesión con GitHub.

El error se produce en un navegador Firefox, al darle al enlace de inicio de sesión con GitHub . Se han seguido los siguientes pasos:

1.- Iniciamos la aplicación en la rama develop.
2.- Introducimos la url 'localhost/booth/1'.
3.- Hacemos click en el enlace de inicio de sesión con la cuenta Github.
4.- Te redirige a la página de inicio y no actúa correctamente.

La traza del error es la siguiente: /error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=K05EHzAFl09SGc6H16N2hCOyXPCb9E5q HTTP/1.1" 200 721

El error debe haberse cometido al hacer el merge con la rama develop, ya que en la rama de github funcionaba correctamente. Debe haberse producido un error en la parte de la redirección.

**Comment by antsuabon** [comment]
El fallo se debe a que no existen las tablas en la base de datos utilizadas por django-social-oauth.

Se puede solucionar lanzando `./manage.py migrate` sobre la aplicación Django. También existe la posibilidad de borrar la base de datos y volverla a crear para evitar inconsistencias.

Al no tratarse de la configuración del entorno y no del desarrollo, no ha sido necesario realizar cambios sobre develop.

**Comment by julsoutos** [comment]
Efectivamente, con la solución del migrate no me ha funcionado, pero borrando la base de datos, creándola y haciendo de nuevo el migrate sí.
