### ISSUE TITLE
Fallo al borrar un usuario

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax/decide#60]
Se produce un fallo al intentar borrar un usuario desde el panel de admin.

El error se produce en un navegador Firefox, al darle a borrar un usuario aleatorio. Se han seguido los siguientes pasos:

1.- Iniciamos la aplicación en la rama develop.
2.- Introducimos la url 'localhost/admin'.
3.- Borramos un usuario previamente creado y que no sea el admin.

La traza del error es la siguiente: 
django.db.utils.ProgrammingError: relation "authentication_emailotpcode" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "authentic...

El error debe haberse cometido al hacer el merge con la rama develop, ya que en la rama de github esta funcionalidad actuaba correctamente.

**Comment by antsuabon** [comment]
El fallo se debe a que la configuración de las tablas en la base de datos no es correcta.

Para solucionarlo se deben seguir los siguientes pasos.
1.- `sudo su - postgres`
2.- `psql -c "drop database <database_name>"`
3.- `psql -c "create database <database_name> owner decide"`
4.- Lanzar `./manage.py migrate` sobre la aplicación Django.

Al no tratarse de la configuración del entorno y no del desarrollo, no ha sido necesario realizar cambios sobre develop.

**Comment by julsoutos** [comment]
Sí, de esa forma se ha resuelto el fallo.
