### ISSUE TITLE
Fallo al contabilizar los votos

### ISSUE THREAD

**Issue by javvazzam** [decide-part-andarax/decide#67]
Se ha encontrado un error 401 al hacer el recuento de una votación con el siguiente mensaje: "string indices must be integer". Se han seguido los siguientes pasos:

-Se ha votado en una votación con el administrador y con un usuario creado
-luego se ha parado la votación y tras contabilizar los votos se ha mostrado el error descrito anteriormente

Este error ha sido descubierto al intentar contabilizar una votación con más de 1 voto; se busca por lo tanto, conseguir hacer el recuento de una votación mas al menos 2 votos.

**Comment by antsuabon** [comment]
Como se puede ver en la siguiente imagen el fallo se autenticación al intentar hacer el recuento de votos sobre una votación cerrada.

![image](https://user-images.githubusercontent.com/48652527/103484089-737b1980-4dec-11eb-847a-c7b1e9cf6155.png)

Se ha podido observar que si se cierra y abre la sesión de administrador, el error desaparece.

**Comment by javvazzam** [comment]
Comprobado. Efectivamente el error se soluciona cerrando y abriendo de nuevo la sesión de administrador.
