### ISSUE TITLE
Fallo en la autenticación por email

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax/decide#80]
Se produce un fallo al intentar hacer el login con el email. 

El error se produce en cualquier navegador (Firefox, Chromium o Opera) . Se han seguido los siguientes pasos:

1.- Descargamos la rama develop.
2.- Nos metemos en cualquier login de booth creando una voting anteriormente. 
3.-Le damos a hacer autenticación por email.
4.- Devuelve un error 500. 

El error debe ser después de haber mergeado porque sé a ciencia cierta que en la rama de la funcionalidad funcionaba.

**Comment by antsuabon** [comment]
El error se debe a que la credenciales de correo estaban ocultas utilizando variables de entorno. 
Para facilitar la prueba y despliegue de la aplicación se ha decidido incorporar las credenciales en el archivo de configuración.

Se ha realizado la corrección en el commit:  #466881f

**Comment by julsoutos** [comment]
De acuerdo. Arreglado.
