### ISSUE TITLE
Generación de ficheros residuales por cada votación

### ISSUE THREAD

**Issue by edubotdom** [decide-part-andarax/decide#86]
Tras haber desarrollado el incremento relacionado al módulo de votación que tiene como objetivo almacenar el resultado del recuento, por cada votación que pasa por este proceso, se genera un fichero derivado del proceso en el que se recoge y queda registrada la información que se ha precisado para realizar el proceso. El problema, recae en que estos ficheros son almacenados en la carpeta votaciones sin control, sin eliminarse las antiguas, por lo que al hacer recuento de un gran número de de votaciones, se genera una gran cantidad de ficheros, uno por votación, que, además son subidos al servidor control de versiones del proyecto, lo que entorpece la labor de desarrollo y llena innecesariamente las carpetas destinadas al desarrollo. 

Se han seguido los siguientes pasos:

1.- Iniciamos la aplicación.
2.- Accedemos a la URL responsable del panel de administración, y accedemos.
3.- Creamos una nueva votación con su título, descripción, pregunta y _auth_.
4. Seleccionamos la recién creada votación y la comenzamos.
5. Detenemos la votación.
6. Pulsamos en hacer el recuento.

Tras realizar esto pasos, finaliza el proceso correctamente, pero podemos apreciar la generación de un nuevo fichero en la carpeta del módulo _voting_ .

Las soluciones que sugiero, son desde mi perspectiva pasan por almacenar dichos ficheros en una carpeta que los almacene para mantenerlos ordenados, e incluir en cualquier caso dichos ficheros en una lista para no subirlos al repositorio de código al ser productos de la actividad de la aplicación.

**Comment by javvazzam** [comment]
Al parecer, al crear el comprimido con los resultados de las votaciones, se estaba indicando una ruta de forma que creaba un archivo .tar dentro del módulo de voting. Esto se ha solucionado con una [modificación](https://github.com/decide-part-andarax/decide/commit/da3f1e33e0c6fb4adb344d2c7b2600493b4f009f) simplemente cambiando la ruta, y se ha creado una carpeta para almacenar los resultados. Además, [se ha añadido esta ruta a gitignore](https://github.com/decide-part-andarax/decide/commit/fe16d3058d28544c3f2bbcf1011baede897ba5da) para que no se suba al repositorio.

**Comment by edubotdom** [comment]
Previo al cierre de esta tarea, he verificado que la incidencia se ha resuelto, por lo que apruebo su finalización.
